### ISSUE TITLE
Scrapy: Guardar únicamente la imagen de IGDB

### ISSUE THREAD

**Issue by Dionakra** [LowPriCEX-devs/lowpricex-lite#1]
Se han realizado algunos cambios en Scrapy, pero no funcionan. Lo que quiero que haga ahora mismo es lo siguiente:

- [x] De IGDB, únicamente obtener la portada del juego, del primero y único que encuentre, y lo guarde
- [x] De CEX, que guarde la portada que exista en un campo portadaCEX en la BD. Éste cambio ya está realizado y se sobreescribe siempre. Quizá debería sobreescribirse solo en cambio de que el campo sea nulo o la URL guardada sea diferente (porque le hayan añadido una URL nueva, por ejemplo)

Esto en cuanto al proceso de Scraping como tal. Como se podrá observar se ha añadido Nintendo Switch a las búsquedas y se ha eliminado el PC de la lista.

**Comment by agubelu** [comment]
Cambios realizados, falta comprobar que la imagen haya cambiado antes de sobreescribirla.

**Comment by Dionakra** [comment]
Yo creo que podemos ir cerrando esto...
