### ISSUE TITLE
Rendimiento: Métricas y configuración del servidor

### ISSUE THREAD

**Issue by Dionakra** [LowPriCEX-devs/lowpricex-lite#7]
Como ya hemos visto en Metronus, es importante tener la página lo más optimizada posible. Para ello, los siguientes tests deben dar las puntuaciones máximas. Algunas cosas se pueden mejorar en el proyecto (css y js) y otras en servidor (gzip, http2 y demás), por lo que se deben optimizar todas las siguientes métricas:

- [ ] [ Google InSights](https://developers.google.com/speed/pagespeed/insights/) - Resultados a 09/04/2017
![image](https://cloud.githubusercontent.com/assets/9566078/24832870/131a55cc-1cba-11e7-8e94-450c0c988a2a.png)
![image](https://cloud.githubusercontent.com/assets/9566078/24832872/1f29299c-1cba-11e7-90ff-138476b09c9d.png)

- [ ] [Grader ](https://website.grader.com/)- Resultados a 09/04/2017
![image](https://cloud.githubusercontent.com/assets/9566078/24832880/5d878814-1cba-11e7-943f-9d53aa75dc9e.png)

- [ ] [GTMetrix](https://gtmetrix.com/reports/lowpricex.info/dfbutShZ) - Resultados a 09/04/2017
![image](https://cloud.githubusercontent.com/assets/9566078/24832884/92cbd502-1cba-11e7-8ae2-933ad85477b0.png)

- [ ] [Dareboost ](https://www.dareboost.com/en/report/58e962310cf2ab834417510b)- Resultados a 09/04/2017
![image](https://cloud.githubusercontent.com/assets/9566078/24832889/ac0db206-1cba-11e7-942f-f0cbd58c090f.png)

- [x] HTTP2 - Resultados a 09/04/2017
![image](https://cloud.githubusercontent.com/assets/9566078/24832892/c8aebf5e-1cba-11e7-8ca6-7caa053b7046.png)

**Comment by agubelu** [comment]
Añadido soporte a HTTP2, compresión GZIP y cacheado de archivos estáticos en el cliente.

**Comment by Dionakra** [comment]
Yo creo que podemos ir cerrando esto...
